---
title: "Netflix View History Data Visuliazation"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(dplyr)
library(DT)
library(tidyr)
library(lubridate)
library(zoo)
library(flexdashboard)
library(shiny)
library(ggplot2)
library(rhandsontable)
library(plotly)
```

Read File
=======================================================================

```{r, echo = FALSE}
fileInput("file1", "Choose CSV File",
                    multiple = TRUE,
                   accept = c("text/csv",
                            "text/comma-separated-values,text/plain",
                            ".csv"))

textInput("username", "username")
actionButton('submit', 'Submit', icon = icon('refresh'))

v <- reactiveValues(t = NULL)

values <- reactiveValues(df_data = NULL)

observeEvent(req(input$file1,input$submit), {
  v$t <- input$username
  values$df_data <- read.csv(input$file1$datapath)
  Netflix <- values$df_data
  Netflix <- Netflix[Netflix$Profile.Name==v$t, ]
  values$post_df_data <- Netflix
  Date <- ymd_hms(Netflix$Start.Time)

  converted_date <- as_date(Date)
  Netflix$Date <- converted_date
  Netflix <- Netflix %>%
  separate(col = Duration, into = c("Duration_0", "Duration_1", "Duration_2"), sep = ':')
  Netflix <- transform(Netflix, Duration_1 = as.numeric(Duration_1))
  Netflix <- Netflix[Netflix$Duration_1 >= 20, ]
  
  Netflix_series <- Netflix %>%
    separate(col = Title, into = c("title", "season", "episode"), sep = ': ')
  
  Netflix_series <- Netflix_series[!is.na(Netflix_series$season),]
  Netflix_series <- Netflix_series[!is.na(Netflix_series$episode),]
  maratones_netflix <- Netflix_series %>%
    count(title, Date)
  
  maratones_netflix  <- maratones_netflix[maratones_netflix$n >= 4,]

  maratones_netflix <- maratones_netflix [order(maratones_netflix$Date),]
 
  maratones_netflix_data <- maratones_netflix  %>% 
    group_by(title) %>% 
    summarise(n = sum(n)) %>%
    arrange(desc(n))
  
  values$maratones_netflix_top <- maratones_netflix_data %>% 
  top_n(10) %>%
  ggplot(aes(x = reorder(title, n), y = n)) +
  geom_col(fill = "#0097d6") +
  coord_flip() +
  ggtitle("Top 10 Binge Watching TV Series") +
  labs(x = "Total Episode", y = "Episode watch time (frequency)") +
  theme_minimal()

  
  netflix_episode_per_day <- Netflix_series %>%
    count(Date) %>%
    arrange(desc(n))
  
  values$netflix_episode_per_day_plot <- ggplot(aes(x = Date, y = n, color = n), 
                                 data = netflix_episode_per_day) +
  geom_col(color = c("#f16727")) +
  theme_minimal() +
  ggtitle("Episodes watched on Netflix per day", "History from 2016 to 2022") +
  labs(x = "Date", y = "Episode") 
  
  netflix_episode_per_day <- netflix_episode_per_day[order(netflix_episode_per_day$Date),]
  netflix_episode_per_day$dat_of_week <- wday(netflix_episode_per_day$Date)
  netflix_episode_per_day$weekdays <- weekdays(netflix_episode_per_day$Date, abbreviate = T)
  netflix_episode_per_day$month <- months(netflix_episode_per_day$Date, abbreviate = T)
  
  netflix_episode_per_day$converted_week <-factor(netflix_episode_per_day$dat_of_week,
                                    levels = rev(1:7),
                                    labels = rev(c("Sun","Mon","Tue","Wed","Thur","Fri","Sat")),
                                    ordered = TRUE) 
  
  netflix_episode_per_day$converted_month <- factor(month(netflix_episode_per_day$Date),
                                   levels = as.character(1:12), 
                                   labels = c("Jan","Feb","March","April","May","June","July","Aug","Sep","Oct","Nov","Dec"),
                                   ordered = TRUE)
  
  netflix_episode_per_day$year <- factor(as.yearmon(netflix_episode_per_day$Date)) 
  netflix_episode_per_day$week <- as.numeric(format(netflix_episode_per_day$Date,"%W"))
  netflix_episode_per_day$weeks <- ceiling(day(netflix_episode_per_day$Date) / 7)
  
  values$netflix_episode_calendar <- ggplot(netflix_episode_per_day, aes(weeks, converted_week, fill = netflix_episode_per_day$n)) + 
  geom_tile(colour = "white") + 
  facet_grid(year(netflix_episode_per_day$Date) ~ converted_month) + 
  scale_fill_gradient(low = "#FFD000", high = "#FF1919") + 
  ggtitle("Episode Calendar Heatmap") +
  labs(x = "Week of Month", y = "Day of the Week") +
  labs(fill = "# Episode") +
  theme(axis.text.y = element_text(size=5, angle=45, hjust=1))
  
  days_of_week <- netflix_episode_per_day %>%
    count(converted_week)


  values$days_of_week_plot <- days_of_week %>% 
    ggplot(aes(x = converted_week, y = n)) +
    geom_col(fill = "#5b59d6") +
    geom_bar(stat="identity") +
    theme(axis.title.x = element_blank(),
              axis.title.y = element_blank(),
              axis.text.y = element_blank(),
              axis.text.x = element_text(face = "bold"),
              plot.title = element_text(size = 18, face = "bold")) 

  
    month_analysis <- netflix_episode_per_day %>%
      count(converted_month)
    
    values$month_plot_plot <- month_analysis %>% 
        ggplot(aes(x = converted_month, y = n)) +
        geom_col(fill = "#808000") +
        geom_bar(stat="identity") +
        theme(axis.title.x = element_blank(),
              axis.title.y = element_blank(),
              axis.text.y = element_blank(),
              axis.text.x = element_text(face = "bold"),
              plot.title = element_text(size = 18, face = "bold")) +
        ggtitle("Frequency sorted based on month") 
})


renderTable(values$post_df_data)


```

Basic Statistics
=======================================================================
Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Top 10 Binge Watching Histogram

```{r}
renderPlotly({values$maratones_netflix_top})
```


### Time Series

```{r}
renderPlotly({values$netflix_episode_per_day_plot})
```

Calendar Heatmap
=======================================================================
-----------------------------------------------------------------------

### Heatmap

```{r}
renderPlotly({values$netflix_episode_calendar})
```

Week statistics
=======================================================================
-----------------------------------------------------------------------

```{r}
renderPlotly({values$days_of_week_plot})
```


Month statistics
=======================================================================
-----------------------------------------------------------------------

```{r}
renderPlotly({values$month_plot_plot})
```